aiosmtpd==1.4.6
cryptography==44.0.2;
portpicker==1.1.0
pytest==6.2.0; python_version<="3.9"
pytest==6.2.5; python_version>="3.10"  # Due to an error with assertion rewrites under 3.10
# Test fixtures
pytest-asyncio==0.11.0; python_version>="3.8"
pytest-timeout==1.0.0
